translation_en:
  default: |
    Unknown error, contact the system administrator
  default_inline:
    - [{"‚ÑπÔ∏è Help": "help"}]
  default_error: |
    ‚ö†Ô∏è <b>System error</b>
    An error occurred while processing the request.
    Please try again later or contact the system administrator.
    
    User ID: <code>{user_id}</code>
    Error log: <code>{last_error.message|fallback:Unknown error}</code>
  access_denied: |
    ‚ùå <b>Access denied</b>
    
    Unfortunately, you do not have permission to use this function.
  access_denied_admin: |
    ‚ùå <b>Access denied</b>
    
    This function is only available to the system administrator.
  success_language: |
    Language set successfully
    For language change at any time, use the /language command
  success_language_inline:
    - [{"üè† Tenant management": "tenant"}, {"‚ÑπÔ∏è Help": "help"}]

translation_ru:
  default: |
    –ù–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –æ—à–∏–±–∫–∞, –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –∫ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä—É —Å–∏—Å—Ç–µ–º—ã
  default_inline:
      - [{"‚ÑπÔ∏è –°–ø—Ä–∞–≤–∫–∞": "help"}]
  default_error: |
    ‚ö†Ô∏è <b>–°–∏—Å—Ç–µ–º–Ω–∞—è –æ—à–∏–±–∫–∞</b>
    
    –ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞ –ø—Ä–∏ –æ–±—Ä–∞–±–æ—Ç–∫–µ –∑–∞–ø—Ä–æ—Å–∞.
    –ü–æ–≤—Ç–æ—Ä–∏—Ç–µ –ø–æ–ø—ã—Ç–∫—É –ø–æ–∑–¥–Ω–µ–µ –∏–ª–∏ –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –∫ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä—É —Å–∏—Å—Ç–µ–º—ã.
    
    ID –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è: <code>{user_id}</code>
    –õ–æ–≥ –æ—à–∏–±–∫–∏: <code>{last_error.message|fallback:–ù–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –æ—à–∏–±–∫–∞}</code>
  access_denied: |
    ‚ùå <b>–î–æ—Å—Ç—É–ø –æ–≥—Ä–∞–Ω–∏—á–µ–Ω</b>
    
    –ö —Å–æ–∂–∞–ª–µ–Ω–∏—é, —É –≤–∞—Å –Ω–µ—Ç –ø—Ä–∞–≤ –¥–ª—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —ç—Ç–æ–π —Ñ—É–Ω–∫—Ü–∏–∏.
  access_denied_admin: |
    ‚ùå <b>–î–æ—Å—Ç—É–ø –æ–≥—Ä–∞–Ω–∏—á–µ–Ω</b>
    
    –≠—Ç–∞ —Ñ—É–Ω–∫—Ü–∏—è –¥–æ—Å—Ç—É–ø–Ω–∞ —Ç–æ–ª—å–∫–æ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä—É —Å–∏—Å—Ç–µ–º—ã.
  success_language: |
    –Ø–∑—ã–∫ —É—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω —É—Å–ø–µ—à–Ω–æ
    –î–ª—è —Å–º–µ–Ω—ã —è–∑—ã–∫–∞ –≤ –ª—é–±–æ–µ –≤—Ä–µ–º—è, –∏—Å–ø–æ–ª—å–∑—É–π—Ç–µ –∫–æ–º–∞–Ω–¥—É /language
  success_language_inline:
    - [{"üè† –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ —Ç–µ–Ω–∞–Ω—Ç–æ–º": "tenant"}, {"‚ÑπÔ∏è –°–ø—Ä–∞–≤–∫–∞": "help"}]