# Telegram Bot configuration for Master tenant (system management)
bot_token: "7164967043:AAH_lHGECZmLB0u1NF_HNVUlnh39oRxSLQQ"
is_active: true

# Bot commands (for BotCommand table)
commands:
  - command: "tenant"
    description: "Menu of tenants"
    scope: "all_private_chats"
  - command: "help"
    description: "Help"
    scope: "all_private_chats"
  - command: "me"
    description: "User information"
    scope: "all_private_chats"